# Generated by Django 3.0.8 on 2020-08-01 11:38

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200801_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_image',
            field=sorl.thumbnail.fields.ImageField(default='/Users/nikitalebediev/Downloads/account.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
