# Generated by Django 3.0.8 on 2020-08-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200801_1138'),
        ('images', '0002_auto_20200801_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='images_liked', to='account.Profile'),
        ),
    ]
