# Generated by Django 3.0.8 on 2020-08-01 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200801_1138'),
        ('images', '0008_auto_20200801_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_user', to='account.Profile'),
        ),
    ]
