# Generated by Django 3.0.8 on 2020-08-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0014_auto_20200803_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_date',
        ),
    ]
